import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { ErrorBoundary } from 'react-error-boundary'

import Calculator from 'components/Calculator'
import ErrorFallback from 'components/ErrorFallback'

const Home: NextPage = () => {
  return (
    <div className="flex items-center min-h-screen bg-secondary-900">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="max-w-md mx-auto">
        <div className="relative h-48">
          <Image
            src="/equal-experts.svg"
            alt="Equal Experts Logo"
            layout="fill"
            objectFit="contain"
            objectPosition="center"
          />
        </div>
        {/* <h1 className="">
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1> */}

        <ErrorBoundary FallbackComponent={ErrorFallback}>
          <Calculator />
        </ErrorBoundary>
      </main>
    </div>
  )
}

export default Home
